create or replace task OBJECT_55.CONDITIONAL_TASK
	warehouse=COMPUTE_WH
	schedule='60 MINUTES'
	when SYSTEM$STREAM_HAS_DATA('OBJECT_55.EMP_STREAM')
	as INSERT INTO OBJECT_55.EMPLOYEE_LOG
SELECT * FROM OBJECT_55.EMPLOYEE;