create or replace task OBJECT_55.EMPLOYEE_SYNC_TASK
	warehouse=COMPUTE_WH
	schedule='60 MINUTES'
	as MERGE INTO OBJECT_55.EMPLOYEE T
USING OBJECT_55.EMPLOYEE_LOG S
ON T.EMP_ID = S.EMP_ID
WHEN MATCHED THEN
    UPDATE SET T.SALARY = S.SALARY;