create or replace pipe OBJECT_55.ENCLOSED_PIPE auto_ingest=false as COPY INTO OBJECT_55.EMPLOYEE
FROM @OBJECT_55.EMPLOYEE_STAGE
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = ''''
);