create or replace view DUMMY4.EMPLOYEE_SUMMARY(
	EMPLOYEE_ID,
	EMPLOYEE_NAME,
	DEPARTMENT,
	SALARY
) as
SELECT
    101 AS EMPLOYEE_ID,
    'Basanta' AS EMPLOYEE_NAME,
    'IT' AS DEPARTMENT,
    50000 AS SALARY;