create or replace view SOUMYAA_1.SRC_CUSTOMER_VW3(
	CUSTOMER_ID,
	CUSTOMER_FIRST_NAME,
	LAST_NAME,
	EMAIL
) as
SELECT
    CUSTOMER_ID,
    FIRST_NAME AS CUSTOMER_FIRST_NAME,
    LAST_NAME,
    EMAIL
FROM SOUMYAA_1.CUSTOMER_VIEW_TEST;