create or replace view SOUMYAA_1.SRC_CUSTOMER_VW2(
	CUSTOMER_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE
) as
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE
FROM SOUMYAA_1.CUSTOMER_VIEW_TEST;