create or replace view SOUMYAA_1.VW_EMPLOYEE_VIEW_194(
	EMPLOYEE_ID,
	FULL_NAME,
	DEPARTMENT_NAME,
	ANNUAL_SALARY,
	LOCATION,
	JOIN_DATE
) as
SELECT
    EMPLOYEE_ID,
    FULL_NAME,
    DEPARTMENT_NAME,
    ANNUAL_SALARY,
    LOCATION,
    JOIN_DATE
FROM SOUMYAA_1.EMPLOYEE_VIEW_193
WHERE ANNUAL_SALARY > 600000;