create or replace view SOUMYAA_1.VW_EMPLOYEE_VIEW_195(
	ID,
	NAME,
	DEPT,
	ANNUAL_PAY,
	WORK_LOCATION,
	START_DATE
) as
SELECT
    EMPLOYEE_ID AS ID,
    FULL_NAME AS NAME,
    DEPARTMENT_NAME AS DEPT,
    ANNUAL_SALARY AS ANNUAL_PAY,
    LOCATION AS WORK_LOCATION,
    JOIN_DATE AS START_DATE
FROM SOUMYAA_1.EMPLOYEE_VIEW_193;