create or replace view SOUMYAA_1.VW_SCHEMA_VIEW_191(
	EMPLOYEE_ID,
	EMPLOYEE_NAME,
	DEPT_NAME,
	EMPLOYEE_SALARY
) as
SELECT
    EMP_ID AS EMPLOYEE_ID,
    EMP_NAME AS EMPLOYEE_NAME,
    DEPARTMENT AS DEPT_NAME,
    SALARY AS EMPLOYEE_SALARY
FROM SOUMYAA_1.SCHEMA_VIEW_189;