CREATE OR REPLACE PROCEDURE BASANTA2.CALCULATE_BONUS()
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    SALARY NUMBER DEFAULT 50000;
    BONUS NUMBER;
BEGIN
    BONUS := SALARY * 10 / 100;
    RETURN BONUS;
END;
';