CREATE OR REPLACE FUNCTION BAIJAYANTI.CHECK_SCORE("SCORE" NUMBER(38,0), "PASS_MARK" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
AS '
    CASE
        WHEN SCORE >= PASS_MARK THEN ''PASS''
        WHEN SCORE >= 35 THEN ''AVERAGE''
        ELSE ''FAIL''
    END
';