create or replace TRANSIENT TABLE TRANSIENT.AUTO_INCREMENT_109 (
	EMP_ID NUMBER(10,0) autoincrement start 100 increment 10 noorder,
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2)
);