create or replace TRANSIENT TABLE TRANSIENT.COLUMN_LVL_UNIQUE_58 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	EMAIL VARCHAR(150),
	PHONE VARCHAR(15),
	DEPARTMENT VARCHAR(50),
	unique (EMP_ID),
	unique (EMAIL),
	unique (PHONE)
);