create or replace TRANSIENT TABLE TRANSIENT.COLUMN_LVL_UNIQUE_56 (
	EMPLOYEE_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	PHONE VARCHAR(15),
	DEPARTMENT VARCHAR(50),
	unique (EMPLOYEE_ID),
	unique (EMAIL),
	unique (PHONE)
);