create or replace TRANSIENT TABLE TRANSIENT.COMPOSITE_PK_TEST_64 (
	EMP_ID NUMBER(38,0) NOT NULL,
	PROJECT_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	PROJECT_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	JOIN_DATE DATE,
	constraint PK_EMP_PROJECT primary key (EMP_ID, PROJECT_ID)
);