create or replace TRANSIENT TABLE TRANSIENT.COMPOSITE_PK_97 (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	PROJECT_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	SALARY NUMBER(10,2),
	DEPARTMENT VARCHAR(100)
);