create or replace TRANSIENT TABLE TRANSIENT.COMPOSITE_PK_TEST_72 (
	EMP_ID_NEW VARCHAR(10),
	PROJECT_ID_NEW VARCHAR(12),
	EMP_NAME VARCHAR(100),
	PROJECT_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	JOIN_DATE DATE
);