create or replace TRANSIENT TABLE TRANSIENT.COURSE_DETAILS_27 (
	COURSE_ID NUMBER(38,0),
	SUBJECT_TITLE VARCHAR(100) NOT NULL DEFAULT 'SQL',
	TRAINER_NAME VARCHAR(100) NOT NULL,
	TRAINING_MODE VARCHAR(50) NOT NULL,
	DURATION_MONTHS NUMBER(38,0)
);