create or replace TRANSIENT TABLE TRANSIENT.COURSE_DETAILS_28 (
	COURSE_ID NUMBER(38,0),
	SUBJECT_TITLE VARCHAR(100) DEFAULT 'SQL',
	TRAINER_NAME VARCHAR(100),
	TRAINING_MODE VARCHAR(50),
	DURATION_MONTHS NUMBER(38,0)
);