create or replace TRANSIENT TABLE TRANSIENT.CUSTOMER_TGT_178 (
	CUSTOMER_ID NUMBER(38,0),
	CUSTOMER_EMAIL VARCHAR(100),
	CUSTOMER_PHONE VARCHAR(20),
	constraint UQ_CUSTOMER_EMAIL_PHONE unique (CUSTOMER_EMAIL, CUSTOMER_PHONE)
);