create or replace TRANSIENT TABLE TRANSIENT.CUSTOMER_13 (
	CUSTOMER_ID_NEW NUMBER(38,0) autoincrement start 2 increment 2 noorder,
	CUSTOMER_NAME VARCHAR(100),
	EMAIL VARCHAR(150),
	PHONE_NUMBER VARCHAR(15)
);