create or replace TRANSIENT TABLE TRANSIENT.DEPARTMENT_76 (
	DEPT_ID_NEW NUMBER(38,0),
	DEPT_NAME VARCHAR(100),
	LOCATION VARCHAR(100),
	NEW_ID NUMBER(38,0) NOT NULL,
	constraint PK_DEPARTMENT primary key (NEW_ID)
);