create or replace TRANSIENT TABLE TRANSIENT."EMPLOYEES SPACE_51" (
	EMP_ID NUMBER(38,0),
	EMP_NAME VARCHAR(100) NOT NULL,
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2) NOT NULL,
	JOIN_DATE DATE NOT NULL
);