create or replace TRANSIENT TABLE TRANSIENT.EMPLOYEE_PK_159 (
	EMP_ID NUMBER(10,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	CITY VARCHAR(50),
	primary key (EMP_ID)
);