create or replace TRANSIENT TABLE TRANSIENT.EMPLOYEE_MASTER_41 (
	EMP_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100),
	DEPARTMENT VARCHAR(50) DEFAULT 'SALES',
	CREATED_DATE DATE DEFAULT CURRENT_TIME(),
	PRIORITY VARCHAR(20) DEFAULT 'high',
	unique (EMAIL),
	primary key (EMP_ID)
);