create or replace TRANSIENT TABLE TRANSIENT.EMPLOYEE_PK_154 (
	EMP_ID NUMBER(10,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50) NOT NULL,
	SALARY NUMBER(10,2),
	CITY VARCHAR(50),
	constraint PK_EMPLOYEE primary key (EMP_ID, DEPARTMENT)
);