create or replace TRANSIENT TABLE TRANSIENT.EMPLOYEE_75 (
	EMP_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPT_ID_NEW NUMBER(38,0),
	SALARY NUMBER(10,2),
	JOIN_DATE DATE,
	constraint PK_EMPLOYEE primary key (EMP_ID)
);