create or replace TRANSIENT TABLE TRANSIENT.EMPLOYEE_BOOLEAN_DEFAULT_133 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	ACTIVE BOOLEAN DEFAULT FALSE,
	IS_PERMANENT BOOLEAN DEFAULT TRUE,
	CITY VARCHAR(50)
);