create or replace TRANSIENT TABLE TRANSIENT.EMPLOYEE_CONSTRAINT_157 (
	EMP_ID NUMBER(10,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	CITY VARCHAR(50),
	constraint PK_EMPLOYEE primary key (EMP_ID)
);