create or replace TRANSIENT TABLE TRANSIENT.PRIMARY_SCENARIO_62 (
	EMPLOYEE_ID VARCHAR(10) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	LOGIN_TIME TIMESTAMP_NTZ(9),
	JOIN_DATE DATE,
	JOIN_TIME TIME(9),
	constraint PK_PRIMARY_SCENARIO_NEW primary key (EMPLOYEE_ID)
);