create or replace TRANSIENT TABLE TRANSIENT.PRIMARY_SCENARIO_63 (
	EMPLOYEE_ID VARCHAR(10),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	LOGIN_TIME TIMESTAMP_NTZ(9),
	JOIN_DATE DATE,
	JOIN_TIME TIME(9)
);