create or replace TRANSIENT TABLE TRANSIENT.PRIMARY_SCENARIO_60 (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	LOGIN_TIME TIMESTAMP_NTZ(9),
	JOIN_DATE DATE,
	JOIN_TIME TIME(9),
	constraint PK_PRIMARY_SCENARIO primary key (EMPLOYEE_ID)
);