create or replace TRANSIENT TABLE TRANSIENT.SALES_TRANSACTION_SOURCE_33 (
	TRANSACTION_ID NUMBER(38,0),
	CUSTOMER_ID VARCHAR(16777216),
	PRODUCT_ID FLOAT,
	TRANSACTION_DATE DATE,
	TOTAL_AMOUNT NUMBER(18,2) COMMENT ' Updated total amount for the transaction',
	STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9)
);