create or replace TRANSIENT TABLE TRANSIENT.STUDENT_DETAILS_21 (
	STUDENT_ID NUMBER(38,0) NOT NULL,
	STUDENT_NAME VARCHAR(100),
	AGE NUMBER(3,0),
	MARKS NUMBER(5,2),
	CITY VARCHAR(50),
	constraint CHK_AGE_VALIDATION check (AGE >= 21),
	constraint CHK_STUDENT_MARKS check (MARKS BETWEEN 35 AND 100),
	constraint CHK_AGE_MARKS check (AGE >= 18 AND MARKS >= 35),
	constraint PK_STUDENT primary key (STUDENT_ID)
);