create or replace TRANSIENT TABLE TRANSIENT.STUDENT_DETAILS_20 (
	STUDENT_ID NUMBER(38,0) NOT NULL,
	STUDENT_NAME VARCHAR(100),
	AGE NUMBER(3,0),
	MARKS NUMBER(5,2),
	CITY VARCHAR(50),
	constraint CHK_AGE_VALIDATION check (AGE >= 21),
	constraint PK_STUDENT primary key (STUDENT_ID)
);