create or replace TRANSIENT TABLE TRANSIENT.TRAINING_PROGRAM_40 (
	PROGRAM_ID NUMBER(38,0),
	PROGRAM_NAME VARCHAR(100) NOT NULL,
	INSTRUCTOR_NAME VARCHAR(100) NOT NULL,
	PROGRAM_TYPE VARCHAR(50) DEFAULT 'ONLINE',
	DURATION_WEEKS NUMBER(38,0) DEFAULT 8
);