create or replace TRANSIENT TABLE TRANSIENT.TRAINING_PROGRAM_38 (
	PROGRAM_ID NUMBER(38,0) autoincrement start 500 increment 10 noorder,
	PROGRAM_NAME VARCHAR(100) NOT NULL,
	INSTRUCTOR_NAME VARCHAR(100) NOT NULL,
	PROGRAM_TYPE VARCHAR(50) DEFAULT 'ONLINE',
	DURATION_WEEKS NUMBER(38,0) DEFAULT 8
);