create or replace TRANSIENT TABLE TRANSIENT.TRAINING_PROGRAM_39 (
	PROGRAM_ID NUMBER(38,0) autoincrement start 100 increment 1 noorder,
	PROGRAM_NAME VARCHAR(100) NOT NULL,
	INSTRUCTOR_NAME VARCHAR(100) NOT NULL,
	PROGRAM_TYPE VARCHAR(50) DEFAULT 'ONLINE',
	DURATION_WEEKS NUMBER(38,0) DEFAULT 8
);