create or replace TRANSIENT TABLE TRANSIENT.TYPECASTING_ALL_89 (
	EMP_NAME VARCHAR(100),
	AGE NUMBER(3,0),
	SALARY NUMBER(10,2),
	BONUS FLOAT,
	DEPARTMENT VARCHAR(50),
	IS_ACTIVE BOOLEAN,
	JOIN_DATE DATE,
	JOIN_TIME TIME(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	LAST_LOGIN TIMESTAMP_NTZ(9),
	EVENT_TIME TIMESTAMP_LTZ(9),
	PROFILE_DATA VARIANT,
	EMP_CODE VARCHAR(20),
	EMP_ID VARCHAR(16777216)
);