CREATE OR REPLACE FUNCTION OBJECT_55.CHECK_ATTENDANCE("DAYS_PRESENT" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
AS '
    CASE
        WHEN DAYS_PRESENT >= 25 THEN ''EXCELLENT''
        WHEN DAYS_PRESENT >= 20 THEN ''ELIGIBLE''
        ELSE ''NOT ELIGIBLE''
    END
';