CREATE OR REPLACE FUNCTION OBJECT_55.GET_RATING("SCORE" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Returns employee rating'
AS '
    CASE
        WHEN SCORE >= 80 THEN ''A''
        ELSE ''B''
    END
';