create or replace TABLE DATAA_1.ALL_DATATYPE_UNIQUE_58 (
	ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	SALARY NUMBER(10,2),
	AGE NUMBER(38,0),
	BONUS FLOAT,
	IS_ACTIVE BOOLEAN,
	JOIN_DATE DATE,
	JOIN_TIME TIME(9),
	CREATED_AT TIMESTAMP_NTZ(9),
	EMP_CODE VARCHAR(20),
	PHONE VARCHAR(15),
	constraint UQ_SALARY unique (SALARY),
	constraint UQ_AGE unique (AGE),
	constraint UQ_BONUS unique (BONUS),
	constraint UQ_IS_ACTIVE unique (IS_ACTIVE)
);