create or replace TABLE DATAA_1.BOOLEAN_BINARY_40 (
	ID NUMBER(38,0),
	NAME VARCHAR(20),
	BOOLEAN_COL VARCHAR(10) NOT NULL DEFAULT 'TRUE',
	BINARY_COL VARCHAR(100) NOT NULL,
	BINARY_10_COL VARCHAR(20) NOT NULL
);