create or replace TABLE DATAA_1.BOOLEAN_BINARY_39 (
	ID NUMBER(38,0),
	NAME VARCHAR(20),
	BOOLEAN_COL BOOLEAN NOT NULL DEFAULT TRUE,
	BINARY_COL BINARY(8388608) NOT NULL,
	BINARY_10_COL BINARY(10) NOT NULL
);