create or replace TABLE DATAA_1.DATATYPE_CHECK15 (
	ID NUMBER(38,0),
	NAME VARCHAR(50),
	EMP_BIGINT NUMBER(38,0),
	EMP_INT NUMBER(38,0),
	EMP_SMALLINT NUMBER(38,0),
	EMP_BYTEINT NUMBER(38,0),
	EMP_FLOAT FLOAT,
	EMP_DECIMAL NUMBER(10,2),
	EMP_DOUBLE FLOAT,
	check (EMP_BIGINT > 0),
	check (EMP_INT >= 100),
	check (EMP_SMALLINT BETWEEN 1 AND 100),
	check (EMP_BYTEINT >= 0),
	check (EMP_FLOAT > 0),
	check (EMP_DECIMAL >= 1000),
	check (EMP_DOUBLE BETWEEN 0 AND 1000)
);