create or replace TABLE DATAA_1.DEFAULT_TIME_19 (
	ID NUMBER(38,0),
	NAME VARCHAR(20),
	TIME_COL TIME(9) NOT NULL DEFAULT CURRENT_TIME(),
	TIMESTAMP_COL TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP()
);