create or replace TABLE DATAA_1.DEFAULT_TIME_31 (
	ID NUMBER(38,0) NOT NULL DEFAULT 1,
	FLOAT_COL FLOAT NOT NULL DEFAULT 10.5,
	FLOAT4_COL FLOAT NOT NULL DEFAULT 20.5,
	FLOAT8_COL FLOAT NOT NULL DEFAULT 30.5,
	DOUBLE_COL FLOAT NOT NULL DEFAULT 40.5,
	DOUBLE_PRECISION_COL FLOAT NOT NULL DEFAULT 50.5,
	REAL_COL FLOAT NOT NULL DEFAULT 60.5
);