create or replace TABLE DATAA_1.EMPLOYEE_CHECK16 (
	EMP_ID NUMBER(38,0),
	EMP_NAME VARCHAR(100),
	AGE NUMBER(38,0),
	SALARY NUMBER(10,2),
	STATUS VARCHAR(20),
	JOIN_DATE DATE,
	constraint CK_NAME_START check (EMP_NAME LIKE 'R%'),
	constraint CK_STATUS check (STATUS IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE')),
	constraint CK_JOIN_DATE check (JOIN_DATE >= '2020-01-01')
);