create or replace TABLE DATAA_1.EMPLOYEE_CHECK24 (
	EMP_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100) NOT NULL,
	AGE NUMBER(38,0) NOT NULL,
	SALARY NUMBER(10,2) NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	check (EMP_ID > 0),
	check (LENGTH(EMP_NAME) >= 3),
	check (AGE BETWEEN 18 AND 60),
	check (SALARY > 0),
	check (STATUS IN ('ACTIVE', 'INACTIVE'))
);