create or replace TABLE DATAA_1.EMPLOYEE_CHECK23 (
	EMP_ID NUMBER(38,0),
	EMP_NAME VARCHAR(100),
	AGE NUMBER(38,0) DEFAULT 25,
	SALARY NUMBER(10,2) DEFAULT 30000,
	STATUS VARCHAR(20) DEFAULT 'ACTIVE',
	check (EMP_ID > 0),
	check (AGE >= 18),
	check (SALARY > 0),
	check (STATUS IN ('ACTIVE', 'INACTIVE'))
);