create or replace TABLE DATAA_1.EMPLOYEE_CHECK30 (
	EMP_ID NUMBER(38,0),
	EMP_NAME VARCHAR(100),
	STATUS_CODE NUMBER(38,0),
	constraint CK_STATUS_CODE check (EMP_ID > 0 AND STATUS_CODE IN (1, 2, 3))
);