create or replace TABLE DATAA_1.EMPLOYEE_UNIQUE_59 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	EMAIL VARCHAR(100) NOT NULL,
	PHONE VARCHAR(15) NOT NULL,
	EMP_CODE VARCHAR(20) NOT NULL,
	PAN_NUMBER VARCHAR(20) NOT NULL,
	unique (EMAIL),
	unique (PHONE),
	unique (EMP_CODE),
	unique (PAN_NUMBER)
);