create or replace TABLE DATAA_1.EMPLOYEE_CHECK25 (
	EMP_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100) NOT NULL,
	AGE NUMBER(38,0) NOT NULL DEFAULT 25,
	SALARY NUMBER(10,2) NOT NULL DEFAULT 30000,
	STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	check (EMP_ID > 0),
	check (AGE >= 18),
	check (SALARY > 0),
	check (STATUS IN ('ACTIVE', 'INACTIVE'))
);