create or replace TABLE DATAA_1.EMPLOYEE_CHECK17 (
	EMP_ID NUMBER(38,0),
	EMPLOYEE_NAME VARCHAR(100),
	AGE NUMBER(38,0),
	SALARY NUMBER(10,2),
	STATUS VARCHAR(20),
	EXP NUMBER(38,0),
	check (EMP_ID > 0),
	check (LENGTH(EMPLOYEE_NAME) >= 3),
	check (AGE BETWEEN 18 AND 60),
	check (SALARY > 0),
	check (STATUS IN ('ACTIVE', 'INACTIVE')),
	check (EXP >= 0)
);