create or replace TABLE DATAA_1.NUMBER_DATATYPE_23 (
	ID VARCHAR(50) NOT NULL DEFAULT '1',
	NUMBER_COL VARCHAR(100) NOT NULL DEFAULT '1000',
	INT_COL NUMBER(10,2) NOT NULL DEFAULT 10,
	INTEGER_COL FLOAT NOT NULL DEFAULT 20
);