create or replace TABLE DATAA_1.ORDER_CHECK27 (
	ORDER_ID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	UNIT_PRICE NUMBER(10,2),
	TOTAL_AMOUNT NUMBER(12,2),
	constraint CK_TOTAL_AMOUNT check (TOTAL_AMOUNT = QUANTITY * UNIT_PRICE)
);