create or replace TABLE DATAA_1.PK_ORDER_187 (
	EMP_ID NUMBER(10,0) NOT NULL,
	PROJECT_ID NUMBER(10,0) NOT NULL,
	LOCATION_ID NUMBER(10,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	constraint PK_EMP_PROJECT_LOCATION primary key (EMP_ID, PROJECT_ID, LOCATION_ID)
);