create or replace TABLE DATAA_1.PK_SCENARIO_181 (
	EMP_CODE VARCHAR(20) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	constraint PK_EMP_CODE primary key (EMP_CODE)
);