create or replace TABLE DATAA_1.STRING_DATATYPE_36 (
	VARCHAR_COL VARCHAR(100) DEFAULT 'New VARCHAR',
	VARCHAR_50_COL NUMBER(10,2) DEFAULT 250.75,
	CHAR_COL VARCHAR(5) DEFAULT 'X',
	CHAR_20_COL VARCHAR(30) DEFAULT 'New CHAR Value',
	CHARACTER_COL VARCHAR(10) DEFAULT 'Y',
	CHARACTER_30_COL VARCHAR(40) DEFAULT 'New Character Value',
	STRING_COL VARCHAR(16777216) DEFAULT 'New String Value',
	TEXT_COL VARCHAR(100) DEFAULT 'New Text Value'
);