create or replace TABLE DATAA_1.STRING_DATATYPE_35 (
	VARCHAR_COL VARCHAR(100) DEFAULT 'Default VARCHAR',
	VARCHAR_50_COL NUMBER(10,2) DEFAULT 100.5,
	CHAR_COL VARCHAR(5) DEFAULT 'A',
	CHAR_20_COL VARCHAR(30) DEFAULT 'Default CHAR 20',
	CHARACTER_COL VARCHAR(10) DEFAULT 'B',
	CHARACTER_30_COL VARCHAR(40) DEFAULT 'Default Character 30',
	STRING_COL VARCHAR(16777216) DEFAULT 'Default String',
	TEXT_COL VARCHAR(100) DEFAULT 'Default Text'
);