create or replace TABLE DATAA_1.STUDENT_CHECK11 (
	STUDENT_ID NUMBER(38,0),
	STUDENT_NAME VARCHAR(50),
	MARKS NUMBER(38,0),
	AGE NUMBER(38,0),
	constraint CK_STUDENT_MARKS check (MARKS BETWEEN 0 AND 100)
);