create or replace TABLE DATAA_1.STUDENT_CHECK_13 (
	STUDENT_ID NUMBER(38,0),
	STUDENT_NAME VARCHAR(50),
	MARKS NUMBER(38,0),
	AGE NUMBER(38,0),
	constraint CK_MARKS check (MARKS BETWEEN 0 AND 100),
	constraint CK_AGE check (AGE >= 18)
);