create or replace TABLE DATAA_1.STUDENT_CHECK12 (
	STUDENT_ID NUMBER(38,0),
	STUDENT_NAME VARCHAR(50),
	MARKS NUMBER(38,0),
	AGE NUMBER(38,0),
	COURSE_FEE NUMBER(10,2) NOT NULL,
	constraint CK_STUDENT_MARKS check (MARKS BETWEEN 0 AND 100),
	constraint CK_STUDENT_AGE check (AGE >= 18),
	check (COURSE_FEE > 0)
);