create or replace TABLE DATAA_1.TIMESTAMP_20 (
	ID NUMBER(38,0),
	TIMESTAMP_NTZ_COL TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	TIMESTAMP_LTZ_COL TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	TIMESTAMP_TZ_COL TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP()
);