create or replace view OBJECT_55.EMPLOYEE_SEQ_VIEW_142(
	SEQUENCE_ID,
	EMP_ID,
	EMP_NAME,
	DEPARTMENT,
	SALARY
) as
SELECT
    OBJECT_55.EMP_ID_SEQ_140.NEXTVAL AS SEQUENCE_ID,
    EMP_ID,
    EMP_NAME,
    DEPARTMENT,
    SALARY
FROM OBJECT_55.EMPLOYEE_SEQ_141;