create or replace view OBJECT_55.EMPLOYEE_VIEW_191(
	EMP_ID,
	EMP_NAME,
	DEPARTMENT,
	JOB_TITLE,
	SALARY,
	BONUS,
	EMAIL,
	PHONE,
	JOIN_DATE,
	IS_ACTIVE,
	LOCATION
) as 
SELECT
    EMP_ID,
    EMP_NAME,
    DEPARTMENT,
    JOB_TITLE,
    SALARY,
    BONUS,
    EMAIL,
    PHONE,
    JOIN_DATE,
    IS_ACTIVE,
    LOCATION
FROM OBJECT_55.EMPLOYEE_VIEW_190
WHERE SALARY > 50000
  AND BONUS > 4000
  AND IS_ACTIVE = TRUE
  AND DEPARTMENT = 'IT';