create or replace view OBJECT_55.EMPLOYEE_VIEW_194(
	EMP_ID,
	EMP_NAME,
	DEPARTMENT,
	SALARY,
	BONUS,
	IS_ACTIVE,
	TOTAL_SALARY
) as
SELECT
    EMP_ID,
    EMP_NAME,
    DEPARTMENT,
    SALARY,
    BONUS,
    IS_ACTIVE,
    SALARY + BONUS AS TOTAL_SALARY
FROM OBJECT_55.EMPLOYEE_VIEW_190;