create or replace view OBJECT_55.EMPLOYEE_VIEW_195(
	EMP_ID,
	EMP_NAME,
	DEPARTMENT,
	SALARY,
	BONUS,
	IS_ACTIVE
) as
SELECT
    EMP_ID,
    EMP_NAME,
    DEPARTMENT,
    SALARY,
    BONUS,
    IS_ACTIVE
FROM OBJECT_55.EMPLOYEE_VIEW_190;