create or replace view OBJECT_55.EMPLOYEE_VIEW_186(
	EMP_ID,
	EMP_NAME,
	DEPARTMENT,
	SALARY,
	JOIN_DATE
) as
SELECT
    EMP_ID,
    EMP_NAME,
    DEPARTMENT,
    SALARY,
    JOIN_DATE
FROM OBJECT_55.EMPLOYEE_VIEW_185;