create or replace view OBJECT_55.EMPLOYEE_VIEW_192(
	EMP_ID,
	EMP_NAME,
	DEPARTMENT,
	SALARY,
	BONUS,
	IS_ACTIVE
) as 
SELECT
    EMP_ID,
    EMP_NAME,
    DEPARTMENT,
    SALARY,
    BONUS,
    IS_ACTIVE
FROM OBJECT_55.EMPLOYEE_VIEW_190
WHERE SALARY >= 55000
  AND BONUS >= 5000
  AND IS_ACTIVE = TRUE
  AND DEPARTMENT IN ('HR', 'Finance');