create or replace view OBJECT_55.EMPLOYEE_VIEW_184(
	EMPLOYEE_ID,
	EMPLOYEE_NAME,
	DEPT_NAME,
	EMPLOYEE_SALARY
) as
SELECT
    EMP_ID AS EMPLOYEE_ID,
    EMP_NAME AS EMPLOYEE_NAME,
    DEPARTMENT AS DEPT_NAME,
    SALARY AS EMPLOYEE_SALARY
FROM OBJECT_55.EMPLOYEE_VIEW_181;