create or replace dynamic table OBJECT_55.EMPLOYEE_DYNAMIC_90(
	EMP_ID,
	EMP_NAME,
	DEPARTMENT_ID,
	DEPARTMENT_NAME_1,
	DEPARTMENT_NAME_2,
	SALARY
) target_lag = '1 minute' refresh_mode = INCREMENTAL initialize = ON_CREATE warehouse = COMPUTE_WH
 as
SELECT
    E.EMP_ID,
    E.EMP_NAME,
    E.DEPARTMENT_ID,
    D1.DEPARTMENT_NAME AS DEPARTMENT_NAME_1,
    D2.DEPARTMENT_NAME AS DEPARTMENT_NAME_2,
    E.SALARY
FROM OBJECT_55.EMPLOYEE_SOURCE_82 E
INNER JOIN OBJECT_55.DEPARTMENT_MASTER_83 D1
    ON E.DEPARTMENT_ID = D1.DEPARTMENT_ID
LEFT JOIN OBJECT_55.DEPARTMENT_MASTER_83 D2
    ON E.DEPARTMENT_ID = D2.DEPARTMENT_ID;