create or replace dynamic table OBJECT_55.EMPLOYEE_DYNAMIC_254(
	EMP_ID,
	EMP_NAME,
	EMP_DEPT,
	CITY,
	SALARY,
	SOURCE_DEPT
) target_lag = '1 minute' refresh_mode = AUTO initialize = ON_CREATE warehouse = TEST_WH
 as
SELECT
    E.EMP_ID,
    E.EMP_NAME,
    E.DEPARTMENT AS EMP_DEPT,
    E.CITY,
    E.SALARY,
    D.DEPARTMENT AS SOURCE_DEPT
FROM OBJECT_55.EMPLOYEE_DYNAMIC_SOURCE_243 E
JOIN OBJECT_55.DEPARTMENT_SOURCE_247 D
    ON E.DEPARTMENT = D.DEPARTMENT;