create or replace dynamic table OBJECT_55.EMPLOYEE_DYNAMIC_87(
	EMP_ID,
	EMP_NAME,
	DEPARTMENT_ID,
	DEPARTMENT_NAME,
	SALARY
) target_lag = '1 minute' refresh_mode = INCREMENTAL initialize = ON_CREATE warehouse = COMPUTE_WH
 as
SELECT
    E.EMP_ID,
    E.EMP_NAME,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    E.SALARY
FROM OBJECT_55.EMPLOYEE_SOURCE_82 E
INNER JOIN OBJECT_55.DEPARTMENT_MASTER_83 D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.SALARY >= 30000;