create or replace semantic view OBJECT_55.SEMANTIC_VIEW_58
	tables (
		SALES as OBJECT_55.SEMANTIC_VIEW_TABLE_56
	)
	dimensions (
		SALES.CUSTOMER_NAME as sales.CUSTOMER_NAME,
		SALES.PRODUCT_NAME as sales.PRODUCT_NAME,
		SALES.CATEGORY as sales.CATEGORY,
		SALES.REGION as sales.REGION,
		SALES.SALE_DATE as sales.SALE_DATE
	)
	metrics (
		SALES.GRAND_TOTAL as MAX(sales.TOTAL_AMOUNT),
		SALES.MEAN_SALES as SUM(sales.TOTAL_AMOUNT),
		SALES.LOWEST_SALES as AVG(sales.TOTAL_AMOUNT),
		SALES.HIGHEST_SALES as MIN(sales.TOTAL_AMOUNT),
		SALES.QUANTITY_TOTAL as AVG(sales.QUANTITY),
		SALES.DISCOUNT_TOTAL as MAX(sales.DISCOUNT_AMOUNT),
		SALES.TAX_TOTAL as MIN(sales.TAX_AMOUNT)
	);