create or replace semantic view OBJECT_55.SEMANTIC_VIEW_45
	tables (
		SALES as OBJECT_55.SEMANTIC_VIEW_19
	)
	dimensions (
		SALES.CUSTOMER as sales.CUSTOMER_NAME,
		SALES.PRODUCT_NAME as sales.PRODUCT_NAME,
		SALES.CATEGORY as sales.CATEGORY,
		SALES.REGION as sales.REGION,
		SALES.SALE_DATE as sales.SALE_DATE
	)
	metrics (
		SALES.TOTAL_SALES as SUM(sales.TOTAL_AMOUNT),
		SALES.AVERAGE_SALES as AVG(sales.TOTAL_AMOUNT)
	);