create or replace semantic view OBJECT_55."SEMANTIC_VIEW_59@TEST"
	tables (
		SALES as OBJECT_55.SEMANTIC_VIEW_TABLE_56
	)
	dimensions (
		SALES."CUSTOMER-NAME" as sales.CUSTOMER_NAME,
		SALES."PRODUCT NAME" as sales.PRODUCT_NAME,
		SALES."SALES@CATEGORY" as sales.CATEGORY,
		SALES."SALES_REGION#" as sales.REGION,
		SALES."SALE.DATE" as sales.SALE_DATE
	)
	metrics (
		SALES."TOTAL-SALES" as MAX(sales.TOTAL_AMOUNT),
		SALES."AVERAGE SALES" as SUM(sales.TOTAL_AMOUNT),
		SALES."MIN@SALES" as AVG(sales.TOTAL_AMOUNT),
		SALES."MAX#SALES" as MIN(sales.TOTAL_AMOUNT),
		SALES.TOTAL_QUANTITY$ as AVG(sales.QUANTITY)
	);