create or replace semantic view OBJECT_55.SEMANTIC_VIEW_55
	tables (
		SALES as OBJECT_55.SEMANTIC_VIEW_52
	)
	dimensions (
		SALES.CUSTOMER_NAME as sales.CUSTOMER_NAME,
		SALES.PRODUCT_NAME as sales.PRODUCT_NAME
	)
	metrics (
		SALES.TOTAL_SALES as MAX(sales.TOTAL_AMOUNT),
		SALES.AVERAGE_SALES as SUM(sales.TOTAL_AMOUNT),
		SALES.MIN_SALES as AVG(sales.TOTAL_AMOUNT),
		SALES.MAX_SALES as MIN(sales.TOTAL_AMOUNT),
		SALES.TOTAL_QUANTITY as AVG(sales.QUANTITY),
		SALES.TOTAL_DISCOUNT as MAX(sales.DISCOUNT_AMOUNT)
	);