create or replace TABLE OBJECT_55.DYNAMIC_EMPLOYEE_SOURCE (
	EMP_ID NUMBER(38,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	CITY VARCHAR(50),
	SALARY NUMBER(12,2),
	BONUS NUMBER(10,2),
	JOIN_DATE DATE,
	STATUS VARCHAR(20)
);