create or replace TABLE OBJECT_55.SEMANTIC_VIEW_TABLE_71 (
	SALE_ID NUMBER(38,0),
	CUSTOMER_NAME VARCHAR(100),
	PRODUCT_NAME VARCHAR(100),
	CATEGORY VARCHAR(50),
	REGION VARCHAR(50),
	QUANTITY NUMBER(10,0),
	TOTAL_AMOUNT NUMBER(12,2),
	DISCOUNT_AMOUNT NUMBER(12,2),
	TAX_AMOUNT NUMBER(12,2),
	SALE_DATE DATE,
	PAYMENT_METHOD VARCHAR(30),
	SALES_REP VARCHAR(100)
);