create or replace TABLE OBJECT_55.SEMANTIC_VIEW_19 (
	ID NUMBER(38,0),
	CUSTOMER_NAME VARCHAR(100),
	PRODUCT_NAME VARCHAR(100),
	CATEGORY VARCHAR(50),
	REGION VARCHAR(50),
	QUANTITY NUMBER(10,0),
	TOTAL_AMOUNT NUMBER(12,2),
	SALE_DATE DATE
);