create or replace task BAIJAYANTI.CONDITIONAL_TASK
	warehouse=COMPUTE_WH
	schedule='60 MINUTES'
	when SYSTEM$STREAM_HAS_DATA('BAIJAYANTI.EMP_STREAM')
	as INSERT INTO BAIJAYANTI.EMPLOYEE_LOG
SELECT * FROM BAIJAYANTI.EMPLOYEE;