create or replace TABLE BAIJAYANTI.EMPLOYEE_121 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	STATUS VARCHAR(20) DEFAULT 'INACTIVE',
	CITY VARCHAR(50)
);