create or replace TABLE BAIJAYANTI.EMPLOYEE_SOURCE_248 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	CITY VARCHAR(50),
	SALARY NUMBER(10,2),
	JOIN_DATE DATE,
	STATUS VARCHAR(20)
);