create or replace TABLE BAIJAYANTI.EMPLOYEE_BOOLEAN_DEFAULT_123 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	IS_PERMANENT BOOLEAN DEFAULT FALSE,
	CITY VARCHAR(50)
);