create or replace dynamic table BAIJAYANTI.EMPLOYEE_DYNAMIC_245(
	EMP_ID,
	EMP_NAME,
	DEPARTMENT,
	CITY,
	SALARY,
	JOIN_DATE,
	STATUS
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = TEST_WH
 as
SELECT EMP_ID, EMP_NAME, DEPARTMENT, CITY, SALARY, JOIN_DATE, STATUS
FROM Baijayanti.EMPLOYEE_DYNAMIC_SOURCE_243;