create or replace dynamic table BAIJAYANTI.EMPLOYEE_DYNAMIC_250(
	EMP_ID,
	EMP_NAME,
	EMP_DEPARTMENT,
	CITY,
	SALARY,
	SOURCE_DEPARTMENT
) target_lag = '1 minute' refresh_mode = AUTO initialize = ON_CREATE warehouse = TEST_WH
 as
SELECT
    E.EMP_ID,
    E.EMP_NAME,
    E.DEPARTMENT as EMP_DEPARTMENT,
    E.CITY,
    E.SALARY,
    D.DEPARTMENT AS SOURCE_DEPARTMENT
FROM Baijayanti.EMPLOYEE_DYNAMIC_SOURCE_243 E
JOIN Baijayanti.DEPARTMENT_SOURCE_247 D
    ON E.DEPARTMENT = D.DEPARTMENT;