create or replace TABLE BASANTA3.EMPLOYEEE (
	EMPLOYEE_ID NUMBER(38,0),
	EMPLOYEE_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	JOB_TITLE VARCHAR(50),
	SALARY NUMBER(10,2),
	JOINING_DATE DATE,
	CITY VARCHAR(50)
);