create or replace TABLE MOD.EMPLOYEE_DROP_122 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50) DEFAULT 'HR',
	SALARY NUMBER(10,2),
	STATUS VARCHAR(20) DEFAULT 'ACTIVE',
	CITY VARCHAR(50)
);