create or replace TABLE ANKITA.CUSTOMER (
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	EMAIL VARCHAR(150),
	PHONE VARCHAR(20),
	CITY VARCHAR(100),
	STATE VARCHAR(100),
	primary key (CUSTOMER_ID)
);