create or replace TABLE ANKITA.DATA_LOAD_REF (
	REF_ID NUMBER(38,0) NOT NULL,
	DATA_LOAD_ID NUMBER(38,0) NOT NULL,
	DESCRIPTION VARCHAR(200),
	STATUS VARCHAR(50),
	CREATED_DATE DATE,
	primary key (REF_ID),
	constraint FK_DATA_LOAD foreign key (DATA_LOAD_ID) references ANKITA.DATA_LOAD(ID)
);