create or replace TABLE SOUMYAA_1.A53 (
	BOOKING_ID NUMBER(38,0),
	GUEST_NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	ROOMS NUMBER(38,0),
	CHECK_IN DATE,
	CHECK_OUT DATE,
	constraint UQ_HOTEL_EMAIL unique (EMAIL),
	constraint UQ_HOTEL_BOOKING_ID unique (BOOKING_ID)
);