create or replace TABLE SOUMYAA_1.CLUSTER_81 cluster by (DEPARTMENT, CITY)(
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	CITY VARCHAR(50),
	SALARY NUMBER(10,2),
	JOIN_DATE DATE,
	STATUS VARCHAR(20)
);