create or replace TABLE SOUMYAA_1.COLUMN_LVL_UNIQUE_57 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	PHONE VARCHAR(15),
	DEPARTMENT VARCHAR(50),
	unique (EMP_ID),
	unique (EMAIL),
	unique (PHONE)
);