create or replace TABLE SOUMYAA_1.COMPOSITE_PK_96 (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	PROJECT_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	SALARY NUMBER(10,2),
	DEPARTMENT VARCHAR(100),
	primary key (EMPLOYEE_ID, PROJECT_ID)
);