create or replace TABLE SOUMYAA_1.COURSE_DETAILS_25 (
	COURSE_ID NUMBER(38,0),
	SUBJECT_TITLE VARCHAR(100) NOT NULL,
	TRAINER_NAME VARCHAR(100) NOT NULL,
	TRAINING_ID NUMBER(38,0) NOT NULL,
	TRAINING_MODE VARCHAR(50) NOT NULL,
	DURATION_MONTHS NUMBER(38,0)
);