create or replace TABLE SOUMYAA_1.COURSE_DETAILS_29 (
	COURSE_ID NUMBER(38,0),
	SUBJECT_TITLE VARCHAR(50) DEFAULT 'SQL',
	TRAINER_NAME VARCHAR(50),
	TRAINING_MODE VARCHAR(20),
	DURATION_MONTHS NUMBER(38,0)
);