create or replace TABLE SOUMYAA_1.CUSTOMER_VIEW_TEST (
	CUSTOMER_ID NUMBER(10,0),
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(100),
	PHONE VARCHAR(20),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	AGE NUMBER(3,0),
	STATUS VARCHAR(20),
	CREATED_DATE DATE,
	SALARY NUMBER(12,2)
);