create or replace TABLE SOUMYAA_1.DEFAULT_10 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50) DEFAULT 'HR',
	CITY VARCHAR(50) DEFAULT 'soro',
	EMP_SAL NUMBER(10,2) DEFAULT 15000,
	CREATED_DATE DATE DEFAULT CURRENT_DATE()
);