create or replace TABLE SOUMYAA_1.DEPARTMENT_78 (
	DEPT_ID NUMBER(38,0) NOT NULL,
	DEPT_NAME VARCHAR(100),
	LOCATION VARCHAR(100),
	NEW_ID NUMBER(38,0) NOT NULL,
	constraint PK_DEPARTMENT primary key (DEPT_ID)
);