create or replace TABLE SOUMYAA_1.EMPLOYEE_PK_166 (
	EMP_ID NUMBER(10,0),
	EMPLOYEE_CODE VARCHAR(20) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	constraint PK_EMPLOYEE primary key (EMPLOYEE_CODE)
);