create or replace TABLE SOUMYAA_1.EMPLOYEE_CONSTRAINT_172 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	CITY VARCHAR(50),
	EMAIL VARCHAR(100) NOT NULL DEFAULT 'unknown@email.com',
	constraint UQ_EMPLOYEE_EMAIL unique (EMAIL)
);