create or replace TABLE SOUMYAA_1.EMPLOYEE_CONSTRAINT_170 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	CITY VARCHAR(50),
	EMAIL VARCHAR(100) NOT NULL,
	constraint UQ_EMPLOYEE_EMAIL unique (EMAIL)
);