create or replace TABLE SOUMYAA_1.EMPLOYEE_TIMESTAMP_DEFAULT_145 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CITY VARCHAR(50)
);