create or replace TABLE SOUMYAA_1.EMPLOYEE_VIEW_193 (
	EMPLOYEE_ID NUMBER(38,0),
	FULL_NAME VARCHAR(150),
	DEPARTMENT_NAME VARCHAR(100),
	ANNUAL_SALARY NUMBER(12,2),
	LOCATION VARCHAR(100),
	JOIN_DATE DATE
);