create or replace TABLE SOUMYAA_1.EMPLOYEE_CURRENT_DATE_127 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	JOINING_DATE DATE DEFAULT CURRENT_DATE(),
	STATUS VARCHAR(20) DEFAULT 'ACTIVE'
);