create or replace TABLE SOUMYAA_1.EMPLOYEE_BOOLEAN_DEFAULT_123 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	IS_ACTIVE BOOLEAN DEFAULT FALSE,
	IS_PERMANENT BOOLEAN DEFAULT TRUE,
	CITY VARCHAR(50)
);