create or replace TABLE SOUMYAA_1.EMPLOYEE_73 (
	EMP_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPT_ID NUMBER(38,0),
	SALARY NUMBER(10,2),
	JOIN_DATE DATE,
	constraint PK_EMPLOYEE primary key (EMP_ID),
	constraint FK_EMPLOYEE_DEPARTMENT foreign key (DEPT_ID) references SOUMYAA_1.DEPARTMENT_73(DEPT_ID)
);