create or replace TABLE SOUMYAA_1.EMPLOYEE_DEFAULT_NULL_131 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50) DEFAULT 'HR',
	SALARY NUMBER(10,2) DEFAULT 50000,
	STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	CITY VARCHAR(50)
);