create or replace TABLE SOUMYAA_1.EMPLOYEE_DEFAULT_NULL_130 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100) NOT NULL,
	DEPARTMENT VARCHAR(50) DEFAULT 'HR',
	SALARY NUMBER(10,2) DEFAULT 50000,
	STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	CITY VARCHAR(50)
);