create or replace TABLE SOUMYAA_1.EMPLOYEE_PK_164 (
	EMP_ID NUMBER(10,0) NOT NULL,
	EMP_CODE VARCHAR(20),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	CITY VARCHAR(50),
	constraint PK_EMPLOYEE primary key (EMP_ID)
);