create or replace TABLE SOUMYAA_1.EMPLOYEE_77 (
	EMP_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPT_ID_NEW NUMBER(38,0),
	SALARY NUMBER(10,2),
	JOIN_DATE DATE,
	NEW_ID NUMBER(38,0),
	constraint PK_EMPLOYEE primary key (EMP_ID),
	constraint FK_EMPLOYEE_DEPARTMENT foreign key (NEW_ID) references SOUMYAA_1.DEPARTMENT_76(NEW_ID)
);