create or replace TABLE SOUMYAA_1.EMPLOYEE_MULTI_DEFAULT_132 (
	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50) DEFAULT ' HR',
	SALARY NUMBER(10,2),
	STATUS VARCHAR(20) DEFAULT 'Active',
	CITY VARCHAR(50) DEFAULT 'cuttack'
);