create or replace TABLE SOUMYAA_1.OBJECT_TABLE_103 (
	EMP_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	EMP_DETAILS OBJECT DEFAULT PARSE_JSON('{department:IT}'),
	CREATED_AT TIMESTAMP_NTZ(9),
	primary key (EMP_ID)
);