create or replace TABLE SOUMYAA_1.OBJECT_DATA (
	EMP_ID OBJECT NOT NULL,
	EMP_NAME VARCHAR(100),
	EMP_DETAILS OBJECT DEFAULT PARSE_JSON('{department:IT}'),
	CREATED_AT TIMESTAMP_NTZ(9),
	primary key (EMP_ID)
);