create or replace TABLE SOUMYAA_1.PRIMARY_KEY_TABLE_49 (
	EMP_ID_NEW VARCHAR(15),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	LOGIN_TIME TIMESTAMP_NTZ(9),
	JOIN_DATE DATE,
	JOIN_TIME TIME(9)
);