create or replace TABLE SOUMYAA_1.PRODUCT_DATA_30 (
	PRODUCT_ID NUMBER(38,0) NOT NULL,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	PRODUCT_CODE VARCHAR(50),
	PRODUCT_INFO VARIANT,
	PRODUCT_DETAILS OBJECT,
	PRICE NUMBER(10,2),
	STATUS VARCHAR(20),
	unique (PRODUCT_CODE),
	check (PRICE > 0)
);