create or replace TABLE SOUMYAA_1.SALES_TRANSACTION_SOURCE_35 (
	TRANSACTION_ID NUMBER(38,0),
	CUSTOMER_ID VARCHAR(16777216),
	PRODUCT_ID FLOAT,
	TRANSACTION_DATE DATE,
	TOTAL_AMOUNT NUMBER(18,2),
	STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9)
)COMMENT='Sales transaction source table'
;