create or replace TABLE SOUMYAA_1.SCENARIO_83 (
	ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(100),
	CODE VARCHAR(10),
	SALARY NUMBER(10,2),
	RATING FLOAT,
	IS_ACTIVE BOOLEAN,
	JOIN_DATE DATE,
	JOIN_TIME TIME(9),
	CREATED_AT TIMESTAMP_NTZ(9)
);