create or replace TABLE SOUMYAA_1.STUDENT_DETAILS_17 (
	STUDENT_ID NUMBER(38,0) NOT NULL,
	STUDENT_NAME VARCHAR(100),
	AGE NUMBER(3,0),
	MARKS NUMBER(5,2),
	CITY VARCHAR(50),
	constraint CHK_STUDENT_AGE check (AGE >= 18),
	constraint CHK_STUDENT_MARKS check (MARKS BETWEEN 0 AND 100),
	constraint PK_STUDENT primary key (STUDENT_ID)
);