create or replace TABLE SOUMYAA_1.TABLE_78 (
	EMP_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPT_ID NUMBER(38,0),
	SALARY NUMBER(10,2),
	JOIN_DATE DATE,
	primary key (EMP_ID),
	foreign key (DEPT_ID) references SOUMYAA_1.DEPARTMENT_78(DEPT_ID)
);