create or replace TABLE SOUMYAA_1.TABLE_79 (
	EMP_ID NUMBER(38,0) NOT NULL,
	EMP_NAME VARCHAR(100),
	DEPT_ID_NEW NUMBER(38,0),
	SALARY NUMBER(10,2),
	JOIN_DATE DATE,
	primary key (EMP_ID),
	foreign key (DEPT_ID_NEW) references SOUMYAA_1.TABLE_1(DEPT_ID_NEW)
);