CREATE OR REPLACE PROCEDURE SOUMYAA_1.CREATE_EMPLOYEE_TABLE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

    CREATE OR REPLACE TABLE EMPLOYEE_SP
    (
        EMP_ID      NUMBER,
        EMP_NAME    VARCHAR(100),
        DEPARTMENT  VARCHAR(50),
        SALARY      NUMBER(10,2)
    );

    RETURN ''EMPLOYEE_SP table created successfully'';

END;
';