CREATE OR REPLACE PROCEDURE SOUMYAA_1.GET_EMPLOYEE_BY_ID("P_EMP_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_EMP_NAME VARCHAR;
BEGIN
    SELECT EMP_NAME
    INTO :V_EMP_NAME
    FROM DEMO.EMPLOYEE
    WHERE EMP_ID = :P_EMP_ID;

    RETURN V_EMP_NAME;
END;
';