CREATE OR REPLACE PROCEDURE SOUMYAA_1.GET_EMPLOYEE_COUNT()
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    EMP_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO :EMP_COUNT
    FROM SOUMYAA_1.EMPLOYEE;

    RETURN EMP_COUNT;
END;
';