create or replace materialized view OBJECT_55.EMPLOYEE_MV_250(
	EMP_ID,
	EMP_NAME,
	SALARY,
	ANNUAL_SALARY
) as
SELECT
    EMP_ID,
    EMP_NAME,
    SALARY,
    SALARY * 12 AS ANNUAL_SALARY
FROM OBJECT_55.EMPLOYEE_MV_SOURCE;