create or replace materialized view OBJECT_55.EMPLOYEE_MV_244(
	EMP_ID,
	EMP_NAME,
	DEPARTMENT,
	CITY,
	SALARY
) as
SELECT
    EMP_ID,
    EMP_NAME,
    DEPARTMENT,
    CITY,
    SALARY
FROM OBJECT_55.EMPLOYEE_MV_SOURCE
WHERE STATUS = 'ACTIVE';