create or replace materialized view OBJECT_55.EMPLOYEE_MV_246(
	EMP_ID,
	EMP_NAME,
	DEPARTMENT,
	SALARY
) as
SELECT
    EMP_ID,
    EMP_NAME,
    DEPARTMENT,
    SALARY
FROM OBJECT_55.EMPLOYEE_MV_SOURCE
WHERE STATUS = 'ACTIVE'
  AND SALARY > 50000;