create or replace materialized view OBJECT_55.EMPLOYEE_MV_243(
	EMP_ID,
	STAFF_NAME,
	DEPARTMENT,
	CITY,
	SALARY
) as
SELECT
    EMP_ID,
    EMP_NAME AS STAFF_NAME,
    DEPARTMENT,
    CITY,
    SALARY
FROM OBJECT_55.EMPLOYEE_MV_SOURCE;