create or replace materialized view OBJECT_55.MV_VIEW_255(
	SALE_ID,
	CUSTOMER_NAME,
	PRODUCT_NAME,
	SALES_AMOUNT
) as
SELECT
    SALE_ID,  
    CUSTOMER_NAME,
    PRODUCT_NAME,
    SALES_AMOUNT
FROM OBJECT_55.MATERIALIZED_VIEW_251;