create or replace TABLE FDALERT.EMPLOYEE_SOURCE (
	EMP_ID NUMBER(38,0),
	EMP_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	SALARY NUMBER(10,2),
	EMAIL VARCHAR(100),
	PHONE_NUMBER VARCHAR(20),
	JOIN_DATE DATE
);