create or replace task PERFORM10.CONDITIONAL_TASK
	warehouse=COMPUTE_WH
	schedule='60 MINUTES'
	when SYSTEM$STREAM_HAS_DATA('SORO.EMP_STREAM')
	as INSERT INTO SORO.EMPLOYEE_LOG
SELECT * FROM SORO.EMPLOYEE;